// FoxAI Browser - profile overrides (copied to profile\foxai\user.js by build.ps1)
user_pref("xpinstall.signatures.required", false);
user_pref("extensions.installDistroAddons", true);
user_pref("extensions.autoDisableScopes", 0);
user_pref("privacy.trackingprotection.enabled", true);
user_pref("privacy.trackingprotection.socialtracking.enabled", true);
user_pref("privacy.trackingprotection.cryptomining.enabled", true);
user_pref("privacy.trackingprotection.fingerprinting.enabled", true);
user_pref("privacy.fingerprintingProtection", true);
user_pref("privacy.fingerprintingProtection.pbmode", true);
user_pref("browser.newtabpage.activity-stream.enabled", false);
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("browser.search.suggest.enabled", false);

// ---- privacy hardening ----
user_pref("extensions.formautofill.addresses.enabled", false);
user_pref("extensions.formautofill.creditCards.enabled", false);
user_pref("browser.formfill.enable", false);
user_pref("network.prefetch-next", false);
user_pref("network.predictor.enabled", false);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.http.referer.defaultPolicy", 0);
user_pref("network.http.referer.trimmingPolicy", 2);
user_pref("network.http.referer.sendRefererHeader", 0);
user_pref("beacon.enabled", false);
user_pref("browser.send_pings", false);
user_pref("device.sensors.enabled", false);
user_pref("dom.battery.enabled", false);
user_pref("media.navigator.enabled", false);
user_pref("media.peerconnection.enabled", false);
user_pref("privacy.firstparty.isolate", true);
user_pref("network.IDN_show_punycode", true);
user_pref("dom.security.https_only_mode", true);
user_pref("network.dns.echconfig.enabled", true);
user_pref("network.http.echconfig.enabled", true);
user_pref("extensions.pocket.enabled", false);
user_pref("signon.rememberSignons", false);
user_pref("browser.uitour.enabled", false);
user_pref("browser.tabs.crashReporting.sendReport", false);
